### Set mouse support
#set -g mouse on 

### Reload config
bind-key r source-file ~/.tmux.conf

### Indexing
set -g renumber-windows on
set -g base-index 1
set -g pane-base-index 1

### Update time every second...
set-option -sg escape-time 0
set-option -g mode-keys vi
set-option -g status-interval 1

#i## Prefix change (Ctrl + Space)
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# ---- ALT KEY BINDS (no prefix) ----

# Alt + 1..9 -> select window
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Use vi keys for pane navigation
bind -n C-h resize-pane -L 1
bind -n C-j resize-pane -D 1
bind -n C-k resize-pane -U 1
bind -n C-l resize-pane -R 1

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Alt + c -> new window
bind -n M-c new-window

# Alt + v -> vertical split
bind -n M-v split-window -h

# Alt + b -> horizontal split
bind -n M-b split-window -v

# *** Style *** 1
set-option -g status-position bottom
set-option -g status-justify left
set-option -g status-left ""
set-option -g status-style "fg=white bg=colour233"
set-option -g window-status-style "bg=colour234"
set-option -g window-status-current-style "bg=colour238"
set-option -g window-status-format " #[fg=colour7]#I #[fg=colour15]#W #[fg=colour196]#F "
set-option -g window-status-current-format "#[fg=colour51] #I #[fg=colour255]#W #[fg=colour46]#F "
set-option -g status-right "#[fg=white bg=colour236] %H:%M #[bg=colour238] %a #[bg=colour240] %d/%m/%Y "


# *** Style *** 2
#set-option -g status-position bottom
#set-option -g status-justify left
#set-option -g status-left ""
#set-option -g status-style "fg=white bg=colour233"
#set-option -g window-status-style "bg=default"
#set-option -g window-status-current-style "bg=default"
#set-option -g window-status-format "#[fg=yellow]#I:#[fg=colour7]#W#[fg=colour196]#F"
#set-option -g window-status-current-format "#[fg=orange]#I:#[fg=colour255]#W#[fg=colour46]#F"
#set-option -g status-right "#[fg=white bg=colour236] %H:%M #[bg=colour238] %a #[bg=colour240] %d/%m/%Y "





