filetype plugin indent on
syntax on
set number
set tabstop=4        
set shiftwidth=4    
set expandtab      
set splitright
set splitbelow
set showmatch
set incsearch       
set clipboard=unnamedplus








